[build]
command = "npm --prefix client ci && npm --prefix client run build"
publish = "client/dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
